In [1]:
#Numpy Array
import numpy as np
x = np.array([2,3,4,5])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[2 3 4 5]


In [2]:
#Trying Coercoins on Arrays
print('numpy can handle different catagorical entities ... \n')
import numpy as np
x = np.array([2,3,'n',5])
print(type(x))
print(x)

numpy can handle different catagorical entities ... 

<class 'numpy.ndarray'>
['2' '3' 'n' '5']


In [12]:
#Numpy Statistical functions
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:\n',a)

a.sum()
np.sum(a)

np.sum(a, axis=0)

Our array is:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


array([ 8, 11, 14])

In [13]:
#Numpy Statistical functions (cont..)
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:\n',a)

a.sum()
np.sum(a)

np.sum(a, axis=-1)

Our array is:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


array([ 6, 12, 15])

In [14]:
#Numpy Statistical functions (cont..)
#Mean
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:\n',a)

a.mean()
np.mean(a)

Our array is:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


3.6666666666666665

In [16]:
#Numpy Statistical functions (cont..)
#Variance
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:\n',a)

a.var()
np.var(a)

Our array is:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


2.2222222222222223

In [17]:
#Numpy Statistical functions (cont..)
#Standard deviation
import numpy as np
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:\n',a)

a.std()
np.std(a)

Our array is:
 [[1 2 3]
 [3 4 5]
 [4 5 6]]


1.4907119849998598

In [20]:
#Materices (Creating a Matrix)
import numpy as np
m1 = np.matrix("1,2,3;4,5,6;7,8,9")
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#Materices (Creating a Matrix) Cont..
#Size of Matrix
import numpy as np
m1 = np.matrix("1,2,3;4,5,6;7,8,9")
print(m1)

m1.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [22]:
#Materices (Creating a Matrix) Cont..
#Size of Matrix
import numpy as np
m1 = np.matrix("1,2,3;4,5,6;7,8,9")
print(m1)

m1.size

[[1 2 3]
 [4 5 6]
 [7 8 9]]


9

In [26]:
#Materices (Creating a Matrix) Cont..
#Size of Matrix
import numpy as np
m1 = np.matrix("1,2,3;4,5,6;7,8,9")
print(m1)

m1.shape[0]
m1.shape[1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [30]:
#Inserting a row and Column to a matrix
import numpy as np
T = np.matrix(np.arange(0,20)).reshape(5,4)
print(T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [2]:
#Inserting row and column to a Matrix
#Creating a new column
import numpy as np
c = np.matrix("3,9,0,8,8")
print(c)

[[3 9 0 8 8]]


In [3]:
#Inserting row and column to a Matrix
#Creating a new row
import numpy as np
r = np.matrix("7,9,8,9")
print(r)

[[7 9 8 9]]


In [4]:
#Inserting row and column to a Matrix
#Adding a new column
import numpy as np
arr = np.insert(T,0,c,axis=1)
print(arr)

NameError: name 'T' is not defined

In [5]:
#Matrix Arithmetic Operations
#Matrix Addition
import numpy as np
n1 = np.matrix([[1,2,3],[4,5,6],[8,9,1]])
n2 = np.matrix([[3,1,3],[4,2,1],[5,1,2]])
print(np.add(n1,n2))

[[ 4  3  6]
 [ 8  7  7]
 [13 10  3]]


In [7]:
#Matrix Arithmetic Operations
#Matrix Substraction
import numpy as np
n1 = np.matrix([[1,2,3],[4,5,6],[8,9,1]])
n2 = np.matrix([[3,1,3],[4,2,1],[5,1,2]])
print(np.subtract(n1,n2))

[[-2  1  0]
 [ 0  3  5]
 [ 3  8 -1]]


In [8]:
#Matrix Arithmetic Operations
#Matrix Multiplication
import numpy as np
n1 = np.matrix([[1,2,3],[4,5,6],[8,9,1]])
n2 = np.matrix([[3,1,3],[4,2,1],[5,1,2]])
print(np.dot(n1,n2))

[[26  8 11]
 [62 20 29]
 [65 27 35]]


In [9]:
#Matrix Arithmetic Operations
#Matrix Division
import numpy as np
n1 = np.matrix([[1,2,3],[4,5,6],[8,9,1]])
n2 = np.matrix([[3,1,3],[4,2,1],[5,1,2]])
print(np.divide(n1,n2))

[[0.33333333 2.         1.        ]
 [1.         2.5        6.        ]
 [1.6        9.         0.5       ]]


In [13]:
#Accessing Data in Matrices
import numpy as np
m1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(m1[1,:])
print(m1[1,2])
print(m1[:,2])

[[4 5 6]]
6
[[3]
 [6]
 [9]]


In [15]:
#Editing Matrices
import numpy as np
m1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(m1)
m1[1,1] = -3
m1[0,2] = 16
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2 16]
 [ 4 -3  6]
 [ 7  8  9]]


In [17]:
#Matrix Linear Algebra
import numpy as np
m1 = np.matrix("0,1,2;3,4,5;6,7,8")
print(m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Matrix Linear Algebra Cont..
#Determinant of matrix
import numpy as np
m1 = np.matrix("0,1,2;3,4,5;6,7,8")
det_matrix = np.linalg.det(m1)
print("Determinent of matrix m1:",det_matrix)

Determinent of matrix m1: 0.0


In [20]:
#Matrix Linear Algebra Cont..
#Rank of matrix
import numpy as np
m1 = np.matrix("0,1,2;3,4,5;6,7,8")
rank_matrix = np.linalg.matrix_rank(m1)
print("Rank of the matrix m1:", rank_matrix)

Rank of the matrix m1: 2


In [2]:
#Matrix Linear Algebra
#Eigen values and vectors of matrix
import numpy as np
m1 = np.matrix("0,1,2;3,4,5;6,7,8")
eig_val, eig_vect = np.linalg.eig(m1)
print(eig_val,"\n",eig_vect)

[ 1.33484692e+01 -1.34846923e+00 -1.15433316e-15] 
 [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [4]:
#Matrix Linear Algebra
#Eigen values only
import numpy as np
m1 = np.matrix("0,1,2;3,4,5;6,7,8")
value1 = np.linalg.eigvals(m1)
print(value1)

[ 1.33484692e+01 -1.34846923e+00 -1.15433316e-15]


In [7]:
#Matrix Linear Algebra
import numpy as np
M = np.matrix("3,1,2;3,2,5;6,7,8")
print(M)
B = np.matrix("2,-1,3").transpose()
print(B)
solve = np.linalg.solve(M,B)
print(solve)

[[3 1 2]
 [3 2 5]
 [6 7 8]]
[[ 2]
 [-1]
 [ 3]]
[[ 1.24242424]
 [ 0.81818182]
 [-1.27272727]]


In [9]:
#Matrix Linear Algebra (Silde 25)
import numpy as np
M = np.matrix("3,1,2;3,2,5;6,7,8")
print(M)
Inv = np.linalg.inv(M)
print(Inv)

[[3 1 2]
 [3 2 5]
 [6 7 8]]
[[ 0.57575758 -0.18181818 -0.03030303]
 [-0.18181818 -0.36363636  0.27272727]
 [-0.27272727  0.45454545 -0.09090909]]


In [11]:
#Eigenvalue Decomposition -I
import numpy as np
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [12]:
#Eigenvalue Decomposition -II
import numpy as np
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)
Q = vectors
print(Q)
R = np.linalg.inv(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]


In [13]:
#Eigenvalue Decomposition -III
import numpy as np
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values, vectors = np.linalg.eig(A)
print(values)
print(vectors)
L = np.diag(values)
print(L)
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -9.75918483e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#Completed 